input_boolean:
  alarm_night:
    name: Night set
    icon: mdi:shield-half-full

  alarm_full:
    name: Full set
    icon: mdi:shield

  alarm_outside:
    name: Outside
    icon: mdi:shield-home

automation:
  - alias: Alarm night set armed
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.alarm_night
        from: 'off'
        to: 'on'
    action:
      #- service: rest_command.casatunes_tts
      #  data:
      #    message: "Alarm has been armed home"
      - service: telegram_bot.send_message
        data_template:
          target:
            - !secret telegram_chat_id_alexey
            - !secret telegram_chat_id_marina   
          title: ""
          message: "\U0001F6E1 Alarm has been armed (Night Set)"
      - service: telegram_bot.send_message
        data_template:
          target:
            - !secret telegram_chat_id_neptune
          disable_notification: true 
          title: ""
          message: "\U0001F6E1 Saturn alarm has been armed (Night Set)"

  - alias: Alarm night set disarmed
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.alarm_night
        from: 'on'
        to: 'off'
    action:
      #- service: rest_command.casatunes_tts
      #  data:
      #    message: "Alarm has been disarmed"
      - service: telegram_bot.send_message
        data_template:
          target:
            - !secret telegram_chat_id_alexey
            - !secret telegram_chat_id_marina
          disable_notification: true   
          title: ""
          message: "\U0001F6E1 Alarm has been disarmed (Night Set)"
      - service: telegram_bot.send_message
        data_template:
          target:
            - !secret telegram_chat_id_neptune 
          title: ""
          message: "\U0001F6E1 Saturn alarm has been disarmed (Night Set)"

  - alias: Alarm full set armed
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.alarm_full
        from: 'off'
        to: 'on'
    action:
      - service: input_boolean.turn_on
        entity_id:
          - input_boolean.presence_simulation
          - input_boolean.indoor_motion_notify
          - input_boolean.porch_motion_notify
          - input_boolean.outdoor_motion_notify_video
      - service: telegram_bot.send_message
        data_template:
          target:
            - !secret telegram_chat_id_alexey
            - !secret telegram_chat_id_marina   
          title: ""
          message: "\U0001F6E1 Alarm has been armed (Full Set)"
      - service: telegram_bot.send_message
        data_template:
          target:
            - !secret telegram_chat_id_neptune 
          title: ""
          message: "\U0001F6E1 Saturn alarm has been armed (Full Set)"

  - alias: Alarm full set disarmed
    initial_state: 'on'
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.alarm_full
        from: 'on'
        to: 'off'
    action:
      - service: input_boolean.turn_off
        entity_id:
          - input_boolean.presence_simulation
          - input_boolean.indoor_motion_notify
          - input_boolean.porch_motion_notify
          - input_boolean.outdoor_motion_notify_video
      #- service: rest_command.casatunes_tts
      #  data:
      #    message: "Alarm has been disarmed"
      - service: telegram_bot.send_message
        data_template:
          target:
            - !secret telegram_chat_id_alexey
            - !secret telegram_chat_id_marina
          disable_notification: true   
          title: ""
          message: "\U0001F6E1 Alarm has been disarmed (Full Set)"
      - service: telegram_bot.send_message
        data_template:
          target:
            - !secret telegram_chat_id_neptune
          title: ""
          message: "\U0001F6E1 Saturn alarm has been disarmed (Full Set)"

