title: Saturn
resources: !include ui/resources.yaml
popup_cards: !include ui/popup_cards.yaml
views:
  - !include ui/ui-overview.yaml
  - !include ui/ui-security.yaml
  - !include ui/ui-cameras.yaml
  - !include ui/ui-music.yaml
  - !include ui/ui-heating.yaml
  - !include ui/ui-rooms.yaml
  - !include ui/ui-admin.yaml