homeassistant:
  customize:
    person.marina:
      entity_picture: /local/users/marina.jpg
    person.alexey:
      entity_picture: /local/users/alexey.jpg
    person.elena:
      entity_picture: /local/users/elena.jpg

  customize_glob:
    binary_sensor.*_presence:
      icon: mdi:home-variant-outline
    binary_sensor.*_mi_band:
      icon: mdi:heart
      
owntracks:
  max_gps_accuracy: 100

input_boolean:
  alexey_home:
    name: Alexey home
    icon: mdi:account

  marina_home:
    name: Marina home
    icon: mdi:account

binary_sensor:
  platform: template
  sensors:
    alexey_presence:
      friendly_name: Alexey
      device_class: presence
      value_template: >-
        {{ is_state('input_boolean.alexey_home', 'on') }}
        
    marina_presence:
      friendly_name: Marina
      device_class: presence
      value_template: >-
        {{ is_state('input_boolean.marina_home', 'on') }}

sensor:
  - platform: google_fit
    name: Alexey
    client_id: !secret google_client_id
    client_secret: !secret google_client_secret

person:
  - name: Alexey
    id: alexey
    device_trackers:
      - device_tracker.alexey_owntracks
      
  - name: Marina
    id: marina
    device_trackers:
      - device_tracker.marina_owntracks

  - name: Elena
    id: elena
    device_trackers:
      - device_tracker.elena_owntracks