homeassistant:
  customize:
    sensor.home_to_office:
      icon: mdi:av-timer
      
    sensor.office_to_home:
      icon: mdi:av-timer

sensor:
  - platform: google_travel_time
    name: Home to Office
    api_key: !secret google_api_key
    origin: zone.home
    destination: zone.office
    options:
      mode: transit
      transit_mode: subway

  - platform: here_travel_time
    app_id: !secret here_app_id
    app_code: !secret here_app_code
    name: Phone To Home
    origin_entity_id: device_tracker.alexey_owntracks
    destination_entity_id: zone.home

  - platform: london_underground
    line:
      - Northern
      - Piccadilly
      - Victoria
      - Jubilee